#!/bin/bash
# +---------------------------------------------------------------------+
# |        _             _ _      ____       _                          |
# |       / \  _   _  __| (_) ___/ ___|  ___(_) ___ _ __   ___ ___      |
# |      / _ \| | | |/ _` | |/ _ \___ \ / __| |/ _ \ '_ \ / __/ _ \     |
# |     / ___ \ |_| | (_| | | (_) |__) | (__| |  __/ | | | (_|  __/     |
# |    /_/   \_\__,_|\__,_|_|\___/____/ \___|_|\___|_| |_|\___\___|     |
# |                                                                     |
# | Copyright Alejandro Olivan 2018                 alex@alexolivan.com |
# +---------------------------------------------------------------------+
# | A Check_mk agent to monitor AudioScience cards on Debian systems    |
# | This file contains plugin agent definition .                        |
# +---------------------------------------------------------------------+
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA  02110-1301, USA.


HPICONTROL="/usr/local/bin/hpicontrol.py"

if hash $HPICONTROL  2>/dev/null; then

    CARDS=`$HPICONTROL list | grep 'Local adapters' | awk '{print $3}'`

    echo '<<<audioscience>>>'
    for (( i=0; i<$CARDS; i++ ))
    do
        ADAPTER="Adapter${i}"
	INFO=`$HPICONTROL -a $i info | head -n 1 | sed 's/^.*\(ASI*\)/\1/g'`
    echo "${ADAPTER}_INFO $INFO"
	TEMP=`$HPICONTROL -a $i cget 11 | grep '\-\-float value' | awk '{print $3}'`
	echo "${ADAPTER}_TEMP $TEMP"
    LOAD=`$HPICONTROL -a $i cget 10 | grep '\-\-int value' | awk '{print $3}'`
    echo "${ADAPTER}_LOAD $LOAD"
    done
fi
