#!/bin/bash
# +---------------------------------------------------------------------+
# |               _                 _            _                      |
# |              | | ___   __ _ ___| |_ __ _ ___| |__                   |
# |              | |/ _ \ / _` / __| __/ _` / __| '_ \                  |
# |              | | (_) | (_| \__ \ || (_| \__ \ | | |                 |
# |              |_|\___/ \__, |___/\__\__,_|___/_| |_|                 |
# |                       |___/                                         |
# |                                                                     |
# | Copyright Alejandro Olivan 2016                 alex@alexolivan.com |
# +---------------------------------------------------------------------+
# | A Check_mk agent to monitor logstash 1.5 on Debian systems          |
# | This file contains plugin agent definition.                         |
# +---------------------------------------------------------------------+
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, 
# MA  02110-1301, USA.


#environment
REDISPORT="6379"

echo "<<<logstash>>>"
#Loop found instances
INSTANCES=`ps aux | grep "[l]ogstash" | awk '{print $2}'`
if [ ! -z "${INSTANCES}" ]; then
        while read line ; do

                REDISCONNS=`netstat -tntap | grep -E "${REDISPORT}.*ESTABLISHED.*${line}.*" | wc -l`
                if [ -z "${REDISCONNS}" ]; then
                        REDISCONNS="nan"
                fi

                SYSUSAGE=`top -b -n 1 -p ${line} | grep ${line} | awk '{print $5, $6, $7, $9, $10, $11}'` 
                if [ -z "${SYSUSAGE}" ]; then
                        SYSUSAGE="nan nan nan nan nan nan"
                fi
                echo "${line} ${REDISCONNS} ${SYSUSAGE}"
        done <<<"$INSTANCES"
fi



