#!/bin/sh
# +---------------------------------------------------------------------+
# |                    _ _                                              |
# |       _ __ ___  __| (_)___       ___  ___ _ ____   _____ _ __       |
# |      | '__/ _ \/ _` | / __|_____/ __|/ _ \ '__\ \ / / _ \ '__|      |
# |      | | |  __/ (_| | \__ \_____\__ \  __/ |   \ V /  __/ |         |
# |      |_|  \___|\__,_|_|___/     |___/\___|_|    \_/ \___|_|         |   
# |                                                                     |
# | Copyright Alejandro Olivan 2016                 alex@alexolivan.com |
# +---------------------------------------------------------------------+
# | A Check_mk agent to monitor redis-server on Debian systems          |
# | This file contains plugin agent definition.                         |
# +---------------------------------------------------------------------+
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, 
# MA  02110-1301, USA.


#environment
PORT=6379

echo '<<<redis>>>'
LISTENIP=`netstat -tlnp | grep ${PORT} | awk '{print $4}' | cut -f1 -d":"`
if hash redis-cli 2>/dev/null; then
    if [ ! -z "${LISTENIP}" ]; then
        redis-cli -h ${LISTENIP} -p ${PORT} info | sed -e 's/:/ /g'
        echo ""
        echo "# System"
        echo "uptime `cat /proc/uptime | awk '{print $1}'`"
    fi
fi