#!/bin/sh
# +---------------------------------------------------------------------+
# |     ____  ____   _____  ____  __  _____  __                         |
# |    |  _ \|  _ \ / _ \ \/ /  \/  |/ _ \ \/ /     _ ____   _____      |
# |    | |_) | |_) | | | \  /| |\/| | | | \  /_____| '_ \ \ / / _ \     |
# |    |  __/|  _ <| |_| /  \| |  | | |_| /  \_____| |_) \ V /  __/     |
# |    |_|   |_| \_\\___/_/\_\_|  |_|\___/_/\_\    | .__/ \_/ \___|     |
# |                                                |_|                  |
# |                                                                     |
# | Copyright Alejandro Olivan 2017                 alex@alexolivan.com |
# +---------------------------------------------------------------------+
# | A Check_mk agent to monitor PROXMOX PVE Hypervisor systems          |
# | This file contains plugin agent definition.                         |
# +---------------------------------------------------------------------+
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA  02110-1301, USA.

echo "<<<proxmoxpve>>>"

# Get PROXMOX PVE local environment facts
echo "pve-version:"
pveversion -v | sed -e 's/:/ /g' | awk '{print $1, $2}'

# Get PROXMOX Cluster info and status
echo "cluster-status:"
pvecm status | sed 's/: */_/g' | sed -r 's/\s+/-/' | sed 's/_/ /g' | sed 's/-$//' | cut -d' ' -f1-2 | awk 'NF>=2'


# Count locally runing VMs and Containers
echo "local-status:"
STOPPEDVMS=`qm list 2>/dev/null | grep "stopped" | wc -l`
echo "stopped-vms ${STOPPEDVMS}"
RUNNINGVMS=`qm list 2>/dev/null | grep "running" | wc -l`
echo "running-vms ${RUNNINGVMS}"

STOPPEDVZS=`vzlist 2>/dev/null | grep "stopped" | wc -l`
echo "stopped-vzs ${STOPPEDVZS}"
RUNNINGVZS=`vzlist 2>/dev/null | grep "running" | wc -l`
echo "running-vzs ${RUNNINGVZS}"

STOPPEDLXCS=`lxc-ls -f 2>/dev/null | grep "STOPPED" | wc -l`
echo "stopped-lxcs ${STOPPEDLXCS}"
RUNNINGLXCS=`lxc-ls -f 2>/dev/null | grep "RUNNING" | wc -l`
echo "running-lxcs ${RUNNINGLXCS}"

