#!/bin/bash
# +---------------------------------------------------------------------+
# |         ____           _                   ____          _          |
# |        / ___|___ _ __ | |_ _____   ____ _ / ___|__ _ ___| |_        |
# |       | |   / _ \ '_ \| __/ _ \ \ / / _` | |   / _` / __| __|       |
# |       | |__|  __/ | | | || (_) \ V / (_| | |__| (_| \__ \ |_        |
# |        \____\___|_| |_|\__\___/ \_/ \__,_|\____\__,_|___/\__|       |
# |                                                                     |
# | Copyright Alejandro Olivan 2016                 alex@alexolivan.com |
# +---------------------------------------------------------------------+
# | A Check_mk agent to monitor CentovaCast server panel on Linux       |
# | This file contains plugin agent definition.                         |
# +---------------------------------------------------------------------+
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston,
# MA  02110-1301, USA.

#Environment
SUMANAGE="/usr/local/centovacast/sbin/sumanage"

echo "<<<centovacast>>>"

VERSION=`${SUMANAGE} version --outputmode=csv | tail -n +2 | head -n -1 | sed -e 's/,/ /g' | awk '{print $1}'`
echo "$VERSION"

ACCOUNT_NAMES=`${SUMANAGE} usage all --outputmode=csv | sed -e 's/,/ /g' | awk '{print $1}' | tail -n +2 | head -n -1`
while read line; do
	USAGE=`${SUMANAGE} usage $line --outputmode=csv | tail -n +2 | head -n -1 | sed -e 's/,/ /g'`
	INFO=`${SUMANAGE} info $line --outputmode=csv | tail -n +2 | head -n -1 | sed -e 's/,/ /g' | awk '{print $2, $3}'`
	echo "$USAGE $INFO"
done <<<"$ACCOUNT_NAMES"