#!/bin/bash
# +---------------------------------------------------------------------+
# |       __        __                          ____  _____             |
# |       \ \      / /____      ________ _     / ___|| ____|            |
# |        \ \ /\ / / _ \ \ /\ / /_  / _` |____\___ \|  _|              |
# |         \ V  V / (_) \ V  V / / / (_| |_____|__) | |___             |
# |          \_/\_/ \___/ \_/\_/ /___\__,_|    |____/|_____|            |
# |                                                                     |
# | Copyright Alejandro Olivan 2016                 alex@alexolivan.com |
# +---------------------------------------------------------------------+
# | A Check_mk agent to monitor Wowza Stream Engine servers on Linux    |
# | This file contains plugin agent definition.                         |
# +---------------------------------------------------------------------+
#
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, 
# MA  02110-1301, USA.

# Environment Variables
host=192.168.192.10
port=8086
user="admin"
password="ladesiempre"
PARSER="./serverinfo.py"
TMPFILE="/tmp/serverinfo"

# Check for parser in place or exit right now
if [ ! -f $PARSER ] ; then
    exit 0
fi

# Check for old data file and clear it if so
if [ -f $TMPFILE ] ; then
    rm $TMPFILE
fi

# Get server stats into new tmp xml file
wget -q --user=${user} --password=${password} http://${host}:${port}/serverinfo -P /tmp

# Check new data file is present and parse it if so
if [ -f $TMPFILE ] ; then
    echo "<<<wowza>>>"
    $PARSER $TMPFILE    
fi